################################################################################
## All
################################################################################

[[builds]]

name = "qbs"

files = [
	"src/qbs.js",
	"src/qbs-util.js",
	"src/qbs-keyboard.js",
	"src/qbs-screen.js",
	"src/qbs-screen-mouse.js",
	"src/qbs-screen-touch.js",
	"src/qbs-screen-commands.js",
	"src/qbs-screen-helper.js",
	"src/qbs-screen-graphics.js",
	"src/qbs-screen-paint.js",
	"src/qbs-screen-bezier.js",
	"src/qbs-screen-images.js",
	"src/qbs-screen-print.js",
	"src/qbs-screen-draw.js",
	"src/qbs-sound.js",
	"src/fonts/font-6x8.js",
	"src/fonts/font-6x6.js",
	"src/fonts/font-8x8.js",
	"src/fonts/font-8x14.js",
	"src/fonts/font-8x16.js",
	"src/qbs-init.js"
]

