name = "cancelInput"
description = "Cancels an input command."
isScreen = true
parameters = [ "name" ]
pdata = [ "The name provided to the input command." ]
seeAlso = [ "input" ]
example = """
$.screen("300x200");
$.print("\\n");
$.input("What is your name?", null, "name");
$.onkey( "Escape", "down", function () {
\t$.print("\\nInput Canceled");
\t$.cancelInput("name");
}, true);"""
