name = "get"
description="Gets an area of pixels from the screen and returns an array of color indices."
isScreen = true
parameters = [ "x1", "y1", "x2", "y2", "tolerance" ]
pdata = [
	"First horizontal coordiante.",
	"First vertical coordinate.",
	"Second horizontal coordiante.",
	"Second vertical coordinate.",
	"[OPTIONAL]. If the color is not in the color palette then attempt to find the closest fit color."
]
seeAlso = [ "put", "setColor" ]
example = """
$.screen("300x200");
$.circle(150, 100, 50, 4);
var colors = $.get(105, 75, 110, 75);
$.print(colors[0].join(","));
"""