name = "getPixel"
description = "Gets the pixel color from the screen and returns the color data."
isScreen = true
parameters = [ "x", "y" ]
pdata = [ "The horizontal coordinate for the pixel", "The vertical coordinate for the pixel" ]
seeAlso = [ "get", "set" ]
example = """
$.screen("300x200");
$.setColor(5);
$.pset(5, 5);
var pixel = $.getPixel(5, 5);
$.print( pixel.s );
"""