name = "getScreen"
description = "Gets the screen based on a screen id."
isScreen = false
parameters = [ "screenId" ]
seeAlso = [ "screen" ]
example = """
$.screen("300x200");
var $screen = $.getScreen(0);
$screen.print("This is screen 0.");
"""