name = "loadSpritesheet"
isScreen = false
parameters = [ "src", "width", "height", "margin", "name" ]
description = """
Loads an image for later use in the drawSprite command. It is recommended to use the ready \
command after loadSpritesheet and before calling the drawSprite command.
"""
pdata = [
	"The source location of an image file or an image element.",
	"The width of each sprite in the spritesheet.",
	"The height of each sprite in the spritesheet.",
	"A margin in pixels around each sprite.",
	"[OPTIONAL]. The name of the sprite for use in the drawSprite command."
]
seeAlso = [
	"drawSprite",
	"loadSpritesheet",
	"ready"
]
example = """
var frame, interval;
$.screen( "300x200" );
$.loadSpritesheet( "monkey.png", 32, 32, 1, "monkey" );
$.ready( function () {
	frame = 0;
	interval = setInterval( run, 500 );
	function run() {
		frame += 1;
		$.cls();
		$.drawSprite( "monkey", frame % 2, 150, 100, 0, 0.5, 0.5 );
	}
	run();
} );"""
onclose = """
clearInterval( interval );
"""
