name = "setColor"
description = "Sets the foreground color."
isScreen = true
parameters = [ "color", "isAddToPalette" ]
pdata = [
	"The color value to set the foreground color.",
	"[OPTIONAL] If set to true and the color is not part of the current color palette then it will add it to the color palette."
]
seeAlso = [ "setBgColor", "setColors" ]
example = """
$.screen( "300x200" );
$.setColor( "green" );
$.line( 300, 0, 0, 200 );
"""
